import type { GraniteResponse, ImpactPath } from "@/types";
import { Download, Copy } from "@phosphor-icons/react";

interface ReportExportProps {
  response: GraniteResponse;
  repoName: string;
  changedFiles: string[];
  diff: string;
}

export default function ReportExport({ response, repoName, changedFiles, diff }: ReportExportProps) {
  const generateMarkdown = () => {
    const paths = response.impactPaths;
    const highRisk = paths.filter((p) => p.riskLevel === "high");
    const mediumRisk = paths.filter((p) => p.riskLevel === "medium");
    const lowRisk = paths.filter((p) => p.riskLevel === "low");

    return `# Impact Analysis Report

**Repository:** ${repoName}
**Overall Risk:** ${response.overallRisk.toUpperCase()}
**Affected Files:** ${response.affectedCount}

---

## Summary

### What Changed
${response.summary.whatChanged}

### What Is At Risk
${response.summary.whatIsAtRisk}

### What To Do
${response.summary.whatToDo}

---

## Impact Paths (${paths.length} total)
${highRisk.length > 0 ? `\n### 🔴 High Risk (${highRisk.length})\n\n${highRisk.map(formatPath).join("\n\n")}` : ""}
${mediumRisk.length > 0 ? `\n### 🟡 Medium Risk (${mediumRisk.length})\n\n${mediumRisk.map(formatPath).join("\n\n")}` : ""}
${lowRisk.length > 0 ? `\n### 🟢 Low Risk (${lowRisk.length})\n\n${lowRisk.map(formatPath).join("\n\n")}` : ""}

---

## Changed Files
${changedFiles.map((f) => `- \`${f}\``).join("\n")}

\`\`\`diff
${diff.slice(0, 2000)}${diff.length > 2000 ? "\n... (truncated)" : ""}
\`\`\`

---

*Generated by ImpactTrace AI Engine*
`;
  };

  const handleDownload = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `impact-analysis-${repoName.replace(/[^a-zA-Z0-9]/g, "-")}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopy = async () => {
    const md = generateMarkdown();
    await navigator.clipboard.writeText(md);
  };

  return (
    <div className="flex items-center gap-2">
      <button
        onClick={handleDownload}
        className="flex items-center gap-1.5 rounded-lg border border-white/5 bg-white/[0.03] px-3 py-2 text-[11px] font-medium text-white/50 hover:bg-white/[0.06] hover:text-white/70 transition-colors"
      >
        <Download size={12} />
        Export Report
      </button>
      <button
        onClick={handleCopy}
        className="flex items-center gap-1.5 rounded-lg border border-white/5 bg-white/[0.03] px-3 py-2 text-[11px] font-medium text-white/50 hover:bg-white/[0.06] hover:text-white/70 transition-colors"
      >
        <Copy size={12} />
        Copy Markdown
      </button>
    </div>
  );
}

function formatPath(p: ImpactPath): string {
  return `- **${p.component}** (${p.dependencyType.replace(/_/g, " ")})
  - Risk: ${p.riskLevel.toUpperCase()}
  - ${p.explanation}
  - Fix: ${p.remediation}`;
}
