import type { GraniteResponse, ImpactPath } from "@/types";
import { DownloadSimple } from "@phosphor-icons/react";

interface Props {
  response: GraniteResponse | null;
  impactPaths: ImpactPath[];
}

export default function ReportExport({ response, impactPaths }: Props) {
  if (!response) return null;

  const handleExport = () => {
    const paths = response.impactPaths || impactPaths;
    if (!paths || paths.length === 0) return;
    const report = generateMarkdown(response, paths);
    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bobs-impact-report-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleExport}
      className="flex items-center gap-1.5 rounded-xl border border-white/8 bg-white/4 px-3 py-2 text-xs font-medium text-text-secondary transition-all hover:border-white/16 hover:bg-white/8 hover:text-text-primary active:scale-95"
    >
      <DownloadSimple size={13} weight="bold" />
      Export report
    </button>
  );
}

function generateMarkdown(response: GraniteResponse, paths: ImpactPath[]): string {
  const riskEmoji = response.overallRisk === "high" ? "🔴" : response.overallRisk === "medium" ? "🟡" : "🟢";
  const rows = paths.map(
    (p) => `| \`${p.component}\` | ${p.dependencyType.replace(/_/g, " ")} | ${p.riskLevel} | ${p.explanation} | ${p.remediation} |`
  ).join("\n");

  return `# Bob's Impact Report

**Generated:** ${new Date().toISOString()}
**Overall Risk:** ${riskEmoji} ${response.overallRisk.toUpperCase()}
**Affected Components:** ${response.affectedCount}
**Powered by:** IBM Bob IDE · watsonx.ai Granite

---

## Summary

### What Changed
${response.summary.whatChanged}

### What Is At Risk
${response.summary.whatIsAtRisk}

### What To Do Before Shipping
${response.summary.whatToDo}

---

## Affected Components

| Component | Dependency Type | Risk | Bob's Explanation | Bob's Recommendation |
|-----------|----------------|------|-------------|-------------|
${rows}

---

*Generated by ImpactTrace — Know what breaks before you ship*
*Powered by IBM Bob IDE · watsonx.ai Granite · IBM TechXchange 2026*
`;
}
