import { GraniteResponse, ImpactPath } from "@/types";

interface ReportExportProps {
  response: GraniteResponse | null;
  impactPaths: ImpactPath[];
}

export default function ReportExport({ response, impactPaths }: ReportExportProps) {
  if (!response) return null;

  const paths = response.impactPaths || impactPaths;

  const handleExport = () => {
    if (!paths || paths.length === 0) return;
    const report = generateMarkdown(response, paths);
    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bobs-impact-report-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleExport}
      className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-sm font-medium text-text-primary transition-colors hover:bg-white/10"
    >
      <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      Export Bob's Report
    </button>
  );
}

function generateMarkdown(response: GraniteResponse, impactPaths: ImpactPath[]): string {
  const riskEmoji = response.overallRisk === "high" ? "🔴" : response.overallRisk === "medium" ? "🟡" : "🟢";

  const paths = impactPaths
    .map(
      (p) =>
        `| \`${p.component}\` | ${p.dependencyType.replace(/_/g, " ")} | ${p.riskLevel} | ${p.explanation} | ${p.remediation} |`
    )
    .join("\n");

  return `# Bob's Impact Report

**Generated:** ${new Date().toISOString()}
**Overall Risk:** ${riskEmoji} ${response.overallRisk.toUpperCase()}
**Affected Components:** ${response.affectedCount}
**Powered by:** IBM Bob IDE

---

## Summary

### What Changed
${response.summary.whatChanged}

### What Is At Risk
${response.summary.whatIsAtRisk}

### What To Do Before Shipping
${response.summary.whatToDo}

---

## Affected Components

| Component | Dependency Type | Risk | Bob's Explanation | Bob's Recommendation |
|-----------|----------------|------|-------------|-------------|
${paths}

---

*Generated by ImpactTrace — Know what breaks before you ship*
*Powered by IBM Bob IDE*
`;
}
